# Site settings
title: Siena Abaya
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

#Collections
collections:
    branches:
      output: true
      permalink: /branches/:name/
